version: '3.8'

services:

  sqlserver-2022:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-2022
    restart: always
    ports:
      - 1433:1433
    environment:
      - MSSQL_SA_PASSWORD=Aa123456
      - ACCEPT_EULA=Y
    volumes:
      - ./SqlServer-2022/BindMounts/data:/var/opt/mssql

  postgresdb-15.4:
    image: postgres:15.4
    container_name: postgresdb-15.4
    restart: always
    ports:
      - 5432:5432
    environment:
      #POSTGRES_USER: someusername //We use the default postgres superuser
      POSTGRES_PASSWORD: Aa123456
      #POSTGRES_DB: mydb //We let the postgres create a default database
    volumes:
       - ./Postgres-15.4/BindMounts/data:/var/lib/postgresql/data

  redisdb-7.2:
    image: redis:7.2.1
    container_name: redisdb-7.2
    restart: always
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=Aa123456
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
    volumes:
      - ./Redis-7.2/BindMounts/data:/data
      - ./Redis-7.2/BindMounts/redis.conf:/usr/local/etc/redis/redis.conf

  mongodb-7:
    image: mongo:7
    container_name: mongodb-7
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: Aa123456
    volumes:
      - ./Mongo-7/BindMounts/data:/data/db
      - ./Mongo-7/BindMounts/config:/data/configdb

  seq-2023.4:
    image: datalust/seq:2023.4
    container_name: seq-2023.4
    restart: always
    ports:
      - 5340:80
      - 5341:5341
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINUSERNAME=admin #A username for the default administrator account
    volumes:
      - ./Seq-2023.4/BindMounts/data:/data

  rabbitmq-3.11:
    image: rabbitmq:3.11-management
    container_name: rabbitmq-3.11
    restart: always
    ports:
        - 5672:5672 # (erlang) communication between the nodes and CLI tool
        - 15672:15672 # communication with the web management API 
    environment:
        - RABBITMQ_DEFAULT_USER=admin
        - RABBITMQ_DEFAULT_PASS=Aa123456
    volumes:
                  # queues and messages data of the container will be stored on the host
                - ./rabbitmq-3.11/BindMounts/data:/var/lib/rabbitmq
                - ./rabbitmq-3.11/BindMounts/log:/var/log/rabbitmq

networks:
  shared-net:

