apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: tracing
  namespace: default
spec:
  tracing:
    samplingRate: "1"
    zipkin: # Note that we are using the Zipkin protocol to talk to Jaeger
      endpointAddress: "http://localhost:9412/api/v2/spans"