apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: ataSecrets
spec:
  type: secretstores.local.file
  version: v1
  metadata:
  - name: secretsFile # Required, example: path/to/file.json
    value: "../.dapr/secrets.json" # The path to the secret store JSON is relative to where you call dapr run.
  - name: nestedSeparator # Optional, Used by the store when flattening the JSON hierarchy to a map. Defaults to ":"
    value: ":"
  - name: multiValued # Optional, "true" sets the multipleKeyValuesPerSecret behavior. Allows one level of multi-valued key/value pairs before flattening JSON hierarchy. Defaults to "false"
    value: "false"